DELETE http://localhost:8080/bookmarks/6
Accept: application/json

###
GET http://localhost:8080/bookmarks?page=1&size=2
Accept: application/json

###
POST http://localhost:8080/bookmarks
Content-Type: application/json

{
  "url": "https://blog.csdn.net/qq_26033289/article/details/81700201",
  "categoryId": "-1"
}

###
